---
- hosts: [slaves]
  tasks:
   - name: Set-up wget
     yum:
       name: wget
       state: latest
     become: true

   - name: Set-up java
     yum:
       name: java
       state: latest
     become: true

   - name: download jenkins.repo
     get_url:
       url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
       dest: /etc/yum.repos.d/jenkins.repo
     become: true 

   - name: import jenkins key
     rpm_key:
       state: present
       key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
     become: true

   - name: install jenkins
     yum:
       name: jenkins
       state: present
     become: true

   - name: start jenkins
     systemd:
       name: jenkins
       state: started
     become: true

   - name: enable jenkins
     systemd:
       name: jenkins
       enabled: true
     become: true
...
